# Generated by Django 3.1.4 on 2020-12-21 12:27

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('members', models.ManyToManyField(null=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
