# Generated by Django 3.1.3 on 2020-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201129_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'کاربری با این ایمیل قبلا ثبت نام کرده است.'}, max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
