# Generated by Django 3.1.3 on 2020-12-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_wallet_user'),
        ('user', '0004_auto_20201213_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='wallet.wallet'),
        ),
    ]
